name = "BasicBlackHoleSim"
uuid = "85eb58d7-e894-4321-a0d0-3cd5d3813362"
version = "0.1.0"
authors = ["jonesdwill <jonesdwill@outlook.com>"]

[deps]
CoherentNoise = "3547b4d8-3bdb-4c10-a099-d01a31e852e0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Noise = "81d43f40-5267-43b7-ae1c-8b967f377efa"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
CoherentNoise = "1.6.6"
ColorSchemes = "3.31.0"
Colors = "0.13.1"
CoordinateTransformations = "0.6.4"
DataFrames = "1.8.1"
DifferentialEquations = "7.17.0"
FileIO = "1.17.1"
ForwardDiff = "1.3.0"
ImageFiltering = "0.7.12"
ImageMagick = "1.4.2"
ImageTransformations = "0.10.2"
Images = "0.26.2"
Interpolations = "0.16.2"
JLD2 = "0.6.3"
LinearAlgebra = "1.12.0"
Noise = "0.3.3"
PlotlyJS = "0.18.17"
Plots = "1.41.2"
Printf = "1.11.0"
ProgressMeter = "1.11.0"
RecursiveArrayTools = "3.39.0"
Revise = "3.12.3"
Test = "1.11.0"
VideoIO = "1.4.0"
